# a list of services to wait for to consider that the launch file
# finished launching
required_services:
  - '/camera_marker_publisher/get_loggers'
  - '/gazebo/get_loggers'
  - '/gazebo_gui/get_loggers'
  - '/{robot_namespace}/b_rep117_laser_filter/get_loggers'
  - '/{robot_namespace}/b_scan_relay/get_loggers'
  - '/{robot_namespace}/ekf_localization_node/get_loggers'
  - '/{robot_namespace}/f_rep117_laser_filter/get_loggers'
  - '/{robot_namespace}/f_scan_relay/get_loggers'
  - '/{robot_namespace}/fake_localization/get_loggers'
  - '/{robot_namespace}/ft_observer/get_loggers'
  - '/{robot_namespace}/gazebo_object_publisher/get_loggers'
  - '/{robot_namespace}/gripper_hw/get_loggers'
  - '/{robot_namespace}/insert_object_node/get_loggers'
  - '/{robot_namespace}/joint_state_publisher/get_loggers'
  - '/{robot_namespace}/move_base_node/get_loggers'
  - '/{robot_namespace}/move_group/get_loggers'
  - '/{robot_namespace}/moveit_macros/get_loggers'
  - '/{robot_namespace}/pick_object_node/get_loggers'
  - '/{robot_namespace}/place_object_node/get_loggers'
  - '/{robot_namespace}/pose_teacher/get_loggers'
  - '/{robot_namespace}/robot_state_publisher/get_loggers'
  - '/pick_pose_selector_node/get_loggers'
  - '/pick_pose_selector_visualiser/get_loggers'
  - '/place_pose_selector_node/get_loggers'
  - '/place_pose_selector_visualiser/get_loggers'
  - '/rosout/get_loggers'
  - '/rqt_simple_launcher_gui_node/get_loggers'
  - '/rviz_gripper_visualizer/get_loggers'
  - '/static_map_server/get_loggers'
  - '/virtual_walls/virtual_walls_map_server/get_loggers'
