#!/usr/bin/env python3

import sys
from rqt_gui.main import Main

plugin = 'rqt_simple_launcher.rqt_simple_launcher.RqtSimpleLauncher'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))
